1.	Create a 1D NumPy array of 10 numbers and print the 3rd element.

In [1]:
import numpy  as np
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a[3])

4


2.	Print the last two elements of a 1D NumPy array using negative indexing.

In [18]:
import numpy  as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[-2:])


[8 9]


3.	Create a 2D array (3×4) and extract the 2nd row.

In [10]:
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [3,2,4,5]])
print(a[1,:])

[5 6 7 8]


4.	From the same 2D array, extract the 1st and 3rd rows.

In [1]:
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [3,2,4,5]])
print(a[[0,2],:])

[[1 2 3 4]
 [3 2 4 5]]


5.	Print the elements from index 2 to 7 in a 1D array.

In [4]:
a=np.array([1,2,3,2,4,2,6,8,6,2,9,7])
print(a[2:8])

[3 2 4 2 6 8]


6.	Get every second element from a 1D array using slicing.

In [7]:
a=np.array([1,2,3,2,4,2,6,8,6,2,9,7])
print(a[::2])

[1 3 4 6 6 9]


7.	Reverse a 1D array using slicing.

In [15]:
a=np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


8.	From a 2D array, extract rows 1 to 2 and columns 2 to 4.

In [17]:
import numpy as np
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])
print(a[1:3,2:4])


[[ 70  80]
 [110 120]]


9.	Print all elements of a NumPy array that are greater than 50.

In [18]:
a=np.array([23,56,87,32])
print(a[a>50])

[56 87]
