creat a 1D arrray

In [3]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


creat 2D array with python list

In [5]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

Create a 1D array from 1 to 10

In [6]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a 1D array from 10 to 50 with step 5

In [7]:
arr=np.arange(10,50,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45])

Create 20 evenly spaced numbers between 5 and 10 using linspace

In [8]:
arr=np.linspace(5,10,20)
arr

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

 Create a 3×4 matrix of all ones

In [9]:
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create a 5×5 identity matrix

In [10]:
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a 2×3 array with random decimals (0 to 1)

In [45]:

arr=np.random.rand(2,3)
print(arr)

[[0.64914405 0.27848728 0.6762549 ]
 [0.59086282 0.02398188 0.55885409]]


 Create an array of 8 random integers between 100 and 200

In [46]:

arr=np.random.randint(100,200,8)
arr

array([169, 197, 129, 124, 162, 107, 143, 133])

Create numbers 0–12 then reshape to 3×4

In [56]:
a=np.arange(0,12)
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Create 10 random integers between 1–9 and make it 2×5

In [75]:
np.random.seed(9)
a=np.random.randint(1,9,10)
b=a.reshape(2,5)
b

array([[7, 5, 7, 6, 7],
       [1, 4, 7, 6, 2]])

Generate array [0–15], convert to 4×4, then extract diagonal

In [73]:
a=np.arange(16)
b=a.reshape(4,4)
d = np.diag(b)
print(b)
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]
