Create a NumPy array of shape (3,4). Print .shape, .ndim, .size, .dtype, .itemsize.

In [5]:
import numpy as np
a=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,1,2,3]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [17]:
print("shape\n",a.shape)
print("ndim\n",a.ndim)
print("size\n",a.size)
print("dtype\n",a.dtype)
print("itemsize",a.itemsize)

shape
 (3, 4)
ndim
 2
size
 12
dtype
 int64
itemsize 8


Create a 1D array of 10 numbers using np.arange() and check its .shape and .ndim

In [20]:
a=np.arange(11)
a
print("shape",a.shape)
print("ndim",a.ndim)

shape (11,)
ndim 1


 Create a 3D array of 2×3×4 and print its .shape, .ndim, .size.

In [27]:
import numpy  as np
a=np.array([
           [[1,2,3,5],
            [4,5,6,5],
            [7,8,9,5]],

           [[10,11,12,5],
            [13,14,15,5],
            [16,17,18,5]]])
print("array",a)
print("shape:",a.shape)
print("ndim:",a.ndim)
print("size:",a.size)

array [[[ 1  2  3  5]
  [ 4  5  6  5]
  [ 7  8  9  5]]

 [[10 11 12  5]
  [13 14 15  5]
  [16 17 18  5]]]
shape: (2, 3, 4)
ndim: 3
size: 24


Create an array of float numbers and display .dtype and .itemsize.

In [30]:
a=np.array([1.2,3.4,5.6])
a
print(a.dtype)
print(a.itemsize)

float64
8
